stages:
  - build
  - deploy

build:
  stage: build
  environment: 
    name: staging
  image: node:12-alpine
  before_script:
    - cd front
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - ./front/build

deploy:
  stage: deploy
  environment: 
    name: staging
  image: python:latest
  script:
    - pip install awscli
    - cd ./front/build
    - aws s3 sync . s3://$AWS_S3_WEB_BUCKET/
